[SLACK_WEBHOOK]
# Webhook supports sending messages
TOKEN = "https://hooks.slack.com/services/THIS_IS_YOUR_DEFAULT_WEBHOOK_KEY"
DUMMY = "https://hooks.slack.com/services/THIS_IS_YOUR_OTHER_WEBHOOK_KEY"


[SLACK_BOT]
# Bot token supports wide of range of scopes (must configure OAuth scope on Slack)
# Please make sure you give it the write Permission Scopes!!
# See https://api.slack.com/scopes
TOKEN = "xoxb-0000000000000-0000000000000-THIS_IS_YOUR_BOT_TOKEN" 


[SLACK_CHANNEL]
# Bot token requires the channel name
SLACK_DEFAULT_CHANNEL_ID = "YOUR_CHOSEN_DEFAULT_CHANNEL_ID"
DUMMY = "YOUR_OTHER_CHANNEL_ID"


[SLACK_USERS]
# Slack user member IDs. See README.md for more information
you  = "<@YOUR_SLACK_ID>"
yourself  = "<@YOURSELF_SLACK_ID>"


[SLACK_NOTIFICATION]
# Mention user on event (ex: @you in slack)
NOTIFY_ON_EVENT =  [ "@you", "@yourself" ]